# Generated by Django 5.1 on 2024-09-20 18:06

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phno', models.CharField(max_length=15, unique=True)),
                ('Password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phno', models.CharField(max_length=15, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('interviewDate', models.DateField(blank=True, null=True)),
                ('interviewTime', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('interviewRole', models.CharField(default='', max_length=255)),
                ('interviewExp', models.CharField(default='', max_length=255)),
                ('techExpertise', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=6, unique=True)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('expiration_time', models.DateTimeField()),
                ('IntId', models.CharField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('interviewId', models.AutoField(primary_key=True, serialize=False)),
                ('interviewRole', models.CharField(max_length=100)),
                ('interviewTechno', models.CharField(max_length=255)),
                ('interviewPayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interviewDate', models.DateField(blank=True, null=True)),
                ('interviewDuration', models.DurationField()),
                ('interviewTime', models.TimeField(blank=True, null=True)),
                ('interview_status', models.CharField(default='Not Taken', max_length=10)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Rel_Cand_Ints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewRole', models.CharField(max_length=100)),
                ('interviewTechno', models.CharField(max_length=255)),
                ('interviewDate', models.DateField(blank=True, null=True)),
                ('interviewDuration', models.DurationField()),
                ('interviewTime', models.TimeField(blank=True, null=True)),
                ('interview_status', models.CharField(default='pending', max_length=10)),
                ('report', models.FileField(blank=True, default=None, null=True, upload_to='pdfs/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.candidate')),
                ('interviews', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.interviews')),
            ],
        ),
        migrations.CreateModel(
            name='Rel_Intw_Ints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewRole', models.CharField(max_length=100)),
                ('interviewTechno', models.CharField(max_length=255)),
                ('interviewPayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interviewDate', models.DateField(blank=True, null=True)),
                ('interviewDuration', models.DurationField()),
                ('interviewTime', models.TimeField(blank=True, null=True)),
                ('interview_status', models.CharField(default='pending', max_length=10)),
                ('payment_status', models.CharField(default='pending', max_length=10)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.interviewer')),
                ('interviews', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.interviews')),
            ],
        ),
    ]
